INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (1,'Odonnell','Tran','Jenette','XNFX375848QGHYZB49',0,3,3,0,7,1,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (2,'Ayala','Abbott','Hilel','GDWS699377TZEYHI24',1,3,8,1,1,2,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (3,'Calhoun','Bradford','Alea','AOUZ829882CUFNVX96',1,1,9,1,29,3,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (4,'Atkinson','Whitehead','Nora','XZUX732272RPPXJS56',0,1,8,1,30,4,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (5,'Ellis','Vincent','Zeph','WSWK221623NXFNJN26',1,3,10,1,17,5,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (6,'Marks','Conley','Tamekah','HGGW976299YIOUEU64',1,1,4,1,4,6,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (7,'Johnson','Riley','Keane','YRMM412572VUYBTK49',1,4,7,1,19,7,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (8,'Forbes','Frazier','Mariko','QGWE658279GGEGDH32',1,4,5,0,21,8,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (9,'Rice','Hayden','Leo','PCZY353171PAQCPV74',1,3,2,0,2,9,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (10,'Odonnell','Woodard','Wendy','TQJV691678LQAFME51',1,2,6,1,31,10,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (11,'Hyde','Paul','Gary','VPDZ724463WEZBSP36',1,4,3,0,22,11,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (12,'Walton','Owen','Evelyn','ZUVK365271FSKBXR83',0,2,9,0,19,12,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (13,'Hendricks','Mendoza','Demetrius','RYRS724673LKPLEA88',1,3,10,0,2,13,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (14,'Espinoza','Benton','Lavinia','UJYA862594NBWHNU14',1,2,6,0,23,14,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (15,'Vang','Pickett','Basia','FRCY131222EMRJOW69',0,1,4,0,4,15,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (16,'Golden','Gordon','Quincy','APZI842877UQIBCW39',1,3,2,0,7,16,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (17,'English','Hatfield','Wyoming','GBBT263122DYTHPN68',0,4,8,1,7,17,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (18,'Slater','Dunn','Amy','ONSK258761TMTBOT26',0,2,10,0,21,18,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (19,'Fowler','Beard','Jackson','HFPD443715NBSOJM72',0,2,3,0,27,19,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (20,'Hess','Webb','Mollie','GHVZ238164HBQVSC22',1,3,9,0,20,20,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (21,'Randolph','Burgess','Kadeem','PMQE897368VGVMWR95',1,4,9,1,28,21,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (22,'Clay','Chandler','Bradley','SPFM763885RTSQPI13',0,4,4,1,20,22,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (23,'Gregory','Rollins','Cade','MXFP792136DJOLDA34',0,1,9,0,30,23,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (24,'Garcia','Holder','Vivien','CJZZ865415LSFXQA46',0,2,8,1,9,24,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (25,'Hardy','Benton','Sonia','ALON912156SKKMYZ22',0,4,8,1,10,25,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (26,'Tate','Manning','Tobias','DBSR392616DGBPGE35',1,4,10,0,30,26,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (27,'Clemons','Velasquez','Stuart','WAHI917685CQLCKZ54',0,4,8,1,6,27,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (28,'Neal','Pickett','Susan','FDPC574259NMOUSS93',0,1,2,1,23,28,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (29,'Fischer','Deleon','Harrison','YRZX669819ECJMQK17',1,1,6,0,6,29,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (30,'Hanson','Everett','Georgia','TPYR875823RWAVPG68',1,1,6,0,19,30,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (31,'Harrison','Terrell','Kendall','OSVY953669OFHDJQ25',0,4,6,0,32,31,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (32,'Mcmahon','Arnold','Carolyn','IQGG972924IFQEPZ55',0,4,5,0,24,32,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (33,'Wells','Gray','Alyssa','MFQQ463837FZLPCE95',1,3,8,1,16,33,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (34,'Monroe','Sosa','Branden','KVYB243716AOTDUF74',1,1,8,1,27,34,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (35,'Stanton','Munoz','Nero','XXWR269419TVKMKB15',0,2,4,1,14,35,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (36,'Vang','Potter','Joy','QVQR453446CPJMMW94',1,1,9,0,11,36,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (37,'Donaldson','Nichols','Branden','KNBV952954LNBHFI13',1,4,5,0,20,37,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (38,'Owen','Padilla','Latifah','HGFC911596HKSGGH99',1,4,2,0,7,38,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (39,'Bartlett','Frederick','Troy','CFPR156522SPSNLU14',0,4,4,0,13,39,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (40,'Vaughn','Owen','Quincy','EBEA867956RRJYFJ33',1,1,4,0,2,40,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (41,'Espinoza','Jones','Timon','YOHH831794CMTLMS78',1,2,2,0,28,41,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (42,'Armstrong','Bruce','Jillian','DVPT635638OWZTGH19',0,4,9,1,26,42,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (43,'Holcomb','Gill','Dominic','RPKI126966UDXHRO89',1,2,7,0,22,43,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (44,'Nash','Marks','Francis','GZZM979847EWITBL35',1,3,2,0,25,44,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (45,'Battle','Hanson','Dorian','JQVJ236734KFZSYR27',0,2,1,0,29,45,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (46,'Lara','Blake','Hayfa','JJFQ757365UTBNDH28',0,2,4,1,8,46,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (47,'Benton','Bauer','Veronica','TJPR131225EJTENJ41',0,4,1,0,1,47,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (48,'Reyes','Ewing','Tamekah','INJK133636FRKIBZ33',1,4,10,1,3,48,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (49,'Fleming','Salazar','Rylee','KNZB162117SXJYHP29',0,2,2,0,7,49,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (50,'Riddle','Pitts','Reed','MVNK365538PCQFET11',0,4,4,0,21,50,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (51,'Suarez','Roberts','Phoebe','ZFQD382347GXXGST51',1,2,10,0,1,51,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (52,'Norton','Mitchell','Harriet','CZFG837934LPUPUM77',1,2,3,0,3,52,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (53,'Washington','Santos','Nathan','YBQW777254CSQCKB34',0,1,6,1,9,53,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (54,'Bernard','Jones','Harriet','CVHJ124128NGGCFJ98',1,3,9,1,3,54,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (55,'Steele','Hunter','Kiara','CENN245366ZNIKZZ59',1,4,2,1,25,55,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (56,'Huffman','Richard','Vladimir','WGAZ972697CXXGVQ74',1,1,10,1,9,56,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (57,'Haney','Sharpe','Maite','WXXU124327RKMVLY32',1,1,4,0,18,57,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (58,'Gay','Cruz','Quemby','SCTW972573LBLUPS91',0,3,9,1,24,58,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (59,'Myers','Tillman','Sasha','BXCP345487YNMHAX21',0,2,9,0,26,59,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (60,'Fuller','Morrow','Quinn','QLYY943358BMBPID81',1,4,7,1,10,60,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (61,'Jenkins','Hewitt','Quemby','RBBI464315IHICHU59',1,2,9,1,6,61,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (62,'Mccullough','Flores','Brynne','QSIW265629QPKTUU29',0,2,8,1,32,62,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (63,'Bender','Odom','Imani','UVZW629683CCVZLP18',0,3,2,0,28,63,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (64,'Floyd','Cline','Evangeline','OSCL666266LUJHBL93',1,1,9,0,15,64,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (65,'Bennett','Velasquez','Alfonso','RVEH646717AUVRLF78',1,2,9,1,24,65,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (66,'Slater','Bailey','Cleo','QUHI262874CYOZRX66',1,2,7,0,31,66,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (67,'Page','Bender','Candice','LKFN259462NDVBHJ73',0,3,9,1,16,67,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (68,'Boyle','Sanford','Rudyard','KISE715596GFEGSE69',0,1,9,1,27,68,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (69,'Hurley','Walters','Camilla','LURT193941DVPBGW86',0,2,4,1,27,69,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (70,'Bonner','Chase','Ifeoma','UAKN115795EYTQRH42',0,2,3,1,14,70,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (71,'Garner','Lucas','Cullen','ZPLL553745LRXRUF36',1,1,7,0,12,71,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (72,'Madden','Hickman','Teagan','PTTM356125BRTTRA16',0,1,8,0,7,72,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (73,'Russo','Delacruz','Isadora','LBHF647236WFUKGD95',0,1,6,0,27,73,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (74,'Berry','Webb','Tanek','PYVF768391VRXQLY58',0,1,7,0,32,74,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (75,'Sykes','Hardin','Fritz','RNQL929284YXKFNS58',1,3,7,1,19,75,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (76,'Hendrix','Harrell','Jolie','NNHV228318JTDXQY82',0,2,3,1,26,76,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (77,'Vinson','Erickson','Nomlanga','TKIF946324ADMCIG36',1,3,10,0,30,77,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (78,'Burns','Wooten','Hannah','XTEV664418CWEEGD84',1,3,3,1,16,78,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (79,'Love','Floyd','Kylynn','JBLV942262CSSATZ96',1,4,2,0,26,79,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (80,'Benton','Holman','Hyatt','FVDJ247535TTQJNE13',1,4,3,0,15,80,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (81,'Ashley','Merritt','Brenda','SNOK689461FPRMEH72',1,3,5,0,23,81,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (82,'Parsons','Silva','Madeson','QNTY917895YLZNHF91',1,4,9,0,16,82,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (83,'Washington','Good','Rhea','HSKR199986GUAJSJ52',1,4,6,1,19,83,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (84,'Burris','Reed','Karen','DXKO195364WOTUOC25',1,4,3,0,3,84,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (85,'Cash','Williams','Adara','PJFY243963CFJPCK69',1,4,6,1,23,85,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (86,'Melton','Cotton','Germane','AGOW896345BIYLFN23',0,4,4,0,15,86,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (87,'Hansen','Hobbs','Yuri','SQQM891146NURSIV81',0,1,10,1,10,87,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (88,'Whitehead','Knight','Moses','BWWK832117MMYWQW42',1,4,9,1,4,88,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (89,'Rosario','Glenn','Gloria','MCHD774836OYHWHD51',0,3,9,1,7,89,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (90,'Ramirez','Cooper','Regan','PYAD873553BLFOGJ43',1,3,6,0,2,90,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (91,'Hendrix','Hinton','Dora','ZIXY488573XEIGDV56',0,4,7,0,9,91,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (92,'Davenport','Woods','Yael','XOWR189972LJGVMU41',0,2,3,0,19,92,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (93,'Cleveland','Stanley','Mia','VDLT467449STCRDY26',0,3,4,1,22,93,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (94,'Holt','Casey','Keith','KXDC592615NUZMFQ88',1,2,2,0,5,94,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (95,'Wooten','Dillard','Macey','KQTL943141GGWJNX25',0,3,5,0,11,95,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (96,'Cherry','Vega','Sylvia','PNBV815822POUTBD82',0,4,3,1,19,96,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (97,'Hebert','Perry','Charissa','PZEC256639VAZEVM23',0,3,10,0,22,97,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (98,'Sexton','Goodman','Dale','QTOW346663FIRCPV87',1,4,3,0,11,98,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (99,'Sherman','Stephenson','Lev','PEYK179193CEUOWN38',1,4,5,1,21,99,TO_DATE('2015-10-23','YYYY-MM-DD'));
INSERT INTO EGRE_EGRESADOS (ID_EGRESADO,AP_PATERNO,AP_MATERNO,NOMBRE,CURP,ID_GENERO,ID_ESTADO_CIVIL,ID_GENTILICIO,RESIDE_MEXICO,ID_ESTADO_NAC,ID_USUARIO,FECHA_REGISTRO) 
VALUES (100,'Maldonado','White','Erica','CSEH251117WMVGKF78',1,4,7,0,17,100,TO_DATE('2015-10-23','YYYY-MM-DD'));
